server:
  port: 8082

spring:
  application:
    name: spring-redis
  datasource:
    url: jdbc:postgresql://localhost:5432/learnings # Replace with your DB name
    username: root                              # Replace with your DB username
    password: sample1                              # Replace with your DB password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update                                   # Options: validate, update, create, create-drop
    show-sql: true                                       # Show SQL queries in the logs
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

